import { iconAPI, iconAuth, iconAutoFix, iconBalance, iconBook, iconBraces, iconBroadcastOn, iconBug, iconBullhorn, iconChat, iconClock, iconCog, iconComment, iconConsole, iconCursor, iconDataTable, iconDesigner, iconEye, iconFile, iconFlag, iconHammer, iconImage, iconKey, iconList, iconLive, iconModel, iconNewspaper, iconQuery, iconRelation, iconRoutes, iconServer, iconStar, iconTable, iconText, iconTextBox, iconTransfer, iconTune, iconVariable, iconWarning, iconWrench } from "./icons";

/**
 * List of icons which may be used by users for
 * customization purposes.
 */
export const USER_ICONS = [
	iconServer,
	iconQuery,
	iconDesigner,
	iconAuth,
	iconAPI,
	iconModel,
	iconCog,
	iconNewspaper,
	iconTable,
	iconStar,
	iconBraces,
	iconFlag,
	iconWrench,
	iconWarning,
	iconBalance,
	iconRoutes,
	iconBook,
	iconList,
	iconClock,
	iconKey,
	iconConsole,
	iconComment,
	iconText,
	iconFile,
	iconHammer,
	iconVariable,
	iconDataTable,
	iconCursor,
	iconTune,
	iconRelation,
	iconBullhorn,
	iconChat,
	iconImage,
	iconBug,
	iconEye,
	iconLive,
	iconTransfer,
	iconBroadcastOn,
	iconAutoFix,
	iconTextBox,
];