// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadConfig() {
  return window['go']['backend']['Surrealist']['LoadConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['backend']['Surrealist']['SaveConfig'](arg1);
}

export function StartDatabase(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['Surrealist']['StartDatabase'](arg1, arg2, arg3, arg4, arg5);
}

export function StopDatabase() {
  return window['go']['backend']['Surrealist']['StopDatabase']();
}

export function TogglePinned() {
  return window['go']['backend']['Surrealist']['TogglePinned']();
}
