// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadConfig():Promise<string>;

export function SaveConfig(arg1:string):Promise<void>;

export function StartDatabase(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string):Promise<void>;

export function StopDatabase():Promise<void>;

export function TogglePinned():Promise<void>;
