blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/surrealdb/docs.surrealdb.com/issues/new/choose
    about: Report issues with the documentation here.
  - name: Security issues
    url: https://surrealdb.com/legal/security
    about: Report security vulnerabilities here.