name: Docker

on:
  push:
    branches: ["main"]
    paths:
      - docker/**
  pull_request:
    branches: ["main"]
    paths:
      - docker/**

env:
  CARGO_TERM_COLOR: always

jobs:
  validate_dockerfile:
    name: Validate Dockerfile
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Check Dockerfile
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          file: docker/Dockerfile
